spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123

  jpa:
    show-sql: true
  freemarker:
    settings:
      classic_compatible: true
appid: wx154a59fa3f782a78

payorder: https://api.mch.weixin.qq.com/pay/unifiedorder

getSessionUrl: https://api.weixin.qq.com/sns/jscode2session?appid=wx154a59fa3f782a78&secret=00d7421d6adb50c8280793bccd2c5436&grant_type=authorization_code&js_code=

filepath: d:/

mybatis:
  mapper-locations: classpath:mappers/*.xml


logging:
  level:
    com.shop.nearby.nearbyshop.dao.WxDao: debug
    com.shop.nearby.nearbyshop.dao.BackDao: debug

